# Generated by Django 4.0.6 on 2022-10-08 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_purchase_total_amt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='total_amt',
            field=models.FloatField(editable=False),
        ),
    ]
